version: '3'

vars:
  PROTO_FILE: "nakama-types.proto"
  PROTO_SERVICE_FILE: "nakama-api.proto"

tasks:
  generate-ue-client-h:
    desc: 'Generate UE Nakama Client Header file.'
    cmds:
    - task: build
    - task: run-codegen
      vars:
        TEMPLATE_FILE: templates/nakama-client-bplib.ue.h.tmpl

  generate-ue-client-cpp:
    desc: 'Generate UE Nakama Client Source file.'
    cmds:
    - task: build
    - task: run-codegen
      vars:
        TEMPLATE_FILE: templates/nakama-client-bplib.ue.cpp.tmpl

  generate-debug:
    desc: 'Debug Codegen parsed info'
    cmds:
    - task: build
    - task: run-codegen
      vars:
        TEMPLATE_FILE: templates/debug.tmpl

  build:
    desc: 'Build the codegen.'
    cmds:
    - cmd: |
        go build

  run-codegen:
    cmds:
    - cmd: |
        ./codegen \
        --template {{.TEMPLATE_FILE}} \
        --proto {{.PROTO_FILE}} \
        --proto-service {{.PROTO_SERVICE_FILE}}

