FROM ue5-source

COPY --chown=ue4:ue4 . /tmp/project
SHELL ["/bin/bash", "-c"]

RUN source Engine/Build/BatchFiles/Linux/SetupEnvironment.sh -dotnet Engine/Build/BatchFiles/Linux && \
    dotnet /home/ue4/UnrealEngine/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll -Project=/tmp/project/NakamaTestApp.uproject \
    NakamaTest Linux Debug

ENTRYPOINT [ "/tmp/project/Binaries/Linux/NakamaTest-Linux-Debug" ]
